config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  resources :bites
  # get 'home/index'
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bite.rb
class Bite < ApplicationRecord
    belongs_to :user
    has_one_attached :image
end

app/models/post.rb
class Post < ApplicationRecord
    has_rich_text :body
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :bites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bites_controller.rb
class BitesController < ApplicationController
  before_action :set_bite, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /bites or /bites.json
  def index
    @bites = Bite.all
  end

  # GET /bites/1 or /bites/1.json
  def show
  end

  # GET /bites/new
  def new
    # @bite = Bite.new
    @bite = current_user.bites.build
  end

  # GET /bites/1/edit
  def edit
  end

  # POST /bites or /bites.json
  def create
    # @bite = Bite.new(bite_params)
    @bite = current_user.bites.build(bite_params)

    respond_to do |format|
      if @bite.save
        format.html { redirect_to bite_url(@bite), notice: "Bite was successfully created." }
        format.json { render :show, status: :created, location: @bite }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bites/1 or /bites/1.json
  def update
    respond_to do |format|
      if @bite.update(bite_params)
        format.html { redirect_to bite_url(@bite), notice: "Bite was successfully updated." }
        format.json { render :show, status: :ok, location: @bite }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bites/1 or /bites/1.json
  def destroy
    @bite.destroy

    respond_to do |format|
      format.html { redirect_to bites_url, notice: "Bite was successfully destroyed." }
      format.json { head :no_content }
    end
  end

def correct_user
  @bite = current_user.bites.find_by(id: params[:id])
  redirect_to bites_path, notice: "Not Authorized to edit this Bite" if @bite.nil?

end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bite
      @bite = Bite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bite_params
      params.require(:bite).permit(:image, :name, :description, :price, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def About
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bites_helper.rb
module BitesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/bites/_bite.html.erb
<div class="biteDisp" id="<%= dom_id bite %>">
    <div class="showImg">
    <%= image_tag(bite.image, class:"bite-image") %>
    </div>
  <div class="showTxt">
    <h2><%= bite.name %></h2>
    <p><%= bite.description %></p>
    <p><strong>Price: $</strong><%= bite.price %></p>
  </div>
</div>

app/views/bites/_form.html.erb
<%= form_with(model: bite, local: true, html: {multipart: true}) do |form| %>
  <% if bite.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bite.errors.count, "error") %> prohibited this bite from being saved:</h2>

      <ul>
        <% bite.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-container">
  <div class="field form-group">
  <%= form.file_field :image, class: "form-control" %>
</div

<br/>
<br/>
  <div class="field form-group">
    <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.text_area :description, class:"form-control", placeholder:"Description" %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.text_field :price, class:"form-control", placeholder:"Price" %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.number_field :user_id, id: :bite_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>
<br/>
  <div>
    <%= form.submit "Submit", class:"btn btn-outline-secondary"%>
  </div>
  </div>
<% end %>

app/views/bites/edit.html.erb
<h1 class="headTxt">Editing bite</h1>

<%= render "form", bite: @bite %>

<br>
<%= button_to "Delete bite", @bite, method: :delete, class:"btn btn-danger link" %>
<br>

<div class="link">
  <%= link_to "Show this bite", @bite  %>  |  
  <%= link_to "Back to bites", bites_path %>

</div>

app/views/bites/index.html.erb
<p style="color: green" class="notice"><%= notice %></p>

<h1 class="headTxt">Bites</h1>
<p class="link">Here you'll find a list of all of our dishes!</p>


<div id="bites" class="showCards">
  <% @bites.each do |bite| %>
    <div class="card" style="width: 20rem;">
      <%= image_tag(bite.image, class:"card-img-top cardImg") %>
      <div class="card-body">
      
        <h5 class="card-title"><%= link_to bite.name, bite%></h5>
        <p class="card-text"><%= bite.description%></p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Price: $<%= bite.price%></li>
      </ul>
    </div>
    <br/>
  <% end %>
</div>

app/views/bites/new.html.erb
<div class="card">
  <div class="card-header">
  <h2>New bite</h2>
  </div>
  <div class="card-body">
<%= render "form", bite: @bite %>
</div>
</div>
<br>

<div>
  <%= link_to "Back to bites", bites_path, class:"link" %>
</div>

app/views/bites/show.html.erb
<%= stylesheet_link_tag 'show', media: 'all', 'data-turbolinks-track': 'reload' %>
<p class="notice"><%= notice %></p>

<%= render @bite %>


  <div class="showPgBtn">
    <%= link_to "Edit bite", edit_bite_path(@bite), class:"btn btn-outline-secondary btn-sm link" %>
    <br/>
    <%= link_to "Back to bites", bites_path, class:"btn btn-outline-secondary btn-sm link" %>
  </div>

app/views/home/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
<div class="carousel-indicators">
<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"></button>
<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"></button>
<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"></button>
<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3"></button>
<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="4"></button>
</div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag '7.jpg', class: 'd-block w-100' %>
    </div>
    <div class="carousel-item">
      <%= image_tag '8.jpg', class: 'd-block w-100' %>
    </div>
    <div class="carousel-item">
      <%= image_tag '10.jpg', class: 'd-block w-100' %>
    </div>
    <div class="carousel-item">
      <%= image_tag '3.jpg', class: 'd-block w-100' %>
    </div>
    <div class="carousel-item">
      <%= image_tag '6.jpg', class: 'd-block w-100' %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/home/_header.html.erb
<%= stylesheet_link_tag 'header' %>
<body class="<%= controller_name == 'about' && action_name == 'index' ? 'about' : '' %>">

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">

  <%= link_to root_path do %>
    <%= image_tag("logo2.png", class: "logo", alt: "My Website Logo") %>
  <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
        <%= link_to "About Us", home_about_path, class: "nav-link"   %>
        </li>
        <li class="nav-item">
        <%= link_to "Bites", bites_path, class: "nav-link"   %>
        </li>

        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to "New Bite", new_bite_path, class: "nav-link"   %>
            </li>
            <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, method: :post, data: { confirm: "Are you sure you want to sign out?" }, class: "nav-link" %>

          </li>
          

            </li>
            <li class="nav-item">
                <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link"   %>
            </li>

        <% else %> 
            <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"   %>
            </li>
            <li class="nav-item">
                <%= link_to "Sign In", new_user_session_path, class: "nav-link"   %>
            </li>
       <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<%= stylesheet_link_tag 'about', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="container">
<h1>About Us</h1>
<p>We believe good food doesn't have to be complicated or expensive. We believe in creating meals that are good to your body and mind, meals that make you feel full and healthy, meals that make you want to brag on social media, meals that will make you want your leftovers (no, really). We believe you can have all of this without spending your whole paycheck, buying a bunch of fancy kitchenware, or spending all day in the kitchen. We believe you can spend less and enjoy more.</p>
<button class="btn btn-outline-light btn-sm">Join our mailing list</button>
<button class="btn btn-outline-light btn-sm">
<%= link_to "Sign Up", new_user_registration_path, class: "nav-link"   %>
</button>
</div>
<%= image_tag 'TB-Headshot.jpg', class: 'headshot' %>
<%= image_tag 'TB-Logo.jpg', class: 'TBlogo' %>

app/views/home/index.html.erb
<%= render 'home/carousel' %>

<div class="pg2">
    <%= image_tag 'logoBlk.png', class: 'logoBlk' %>
    <div class="homeTxt">
        <h1>TimasBite</h1>
        <h6>We think your food should work as hard as you do, so we designed delicious meal plans, with macronutrient profiles to support your fitness and weight goals.</h6>
    </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>TimasBite</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    </head>
  <body>

  <%= render partial: 'home/header' %>

  <div>
  <%= yield %>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.rich_text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>
  <div>
    <strong>Body:</strong>
    <%= post.body %>
  </div>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>